### ISSUE TITLE
Get quiz dishes from the backend

### ISSUE THREAD

**Issue by martenjostmann** [erikzimmermann/mensa-today#127]
Currently we hard coded the dishes in the front end. But we should get them from the back end to be more flexible.

**Comment by lgiesen** [comment]
I updated the dishes from the presentation week. I think this should fix this issue, doesn't it?

**Comment by martenjostmann** [comment]
Yeah but the plan is that we do not hardcode the dishes for the quiz in the frontend

**Comment by lgiesen** [comment]
Ok, this would require an API call for get_dishplan where authorization is not required.
