### ISSUE TITLE
If there are no dishes on the dishplan, there is an 500 Internal Server Error when calling get_recommendations

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#142]
I just rebuilt the docker container and did the migrations and crawled the dishes.

**Comment by lgiesen** [comment]
It could return [] or a specific error that we can catch as an 500 Internal Server Error could also mean something else

**Comment by erikzimmermann** [comment]
I guess this is unintended :D Gonna check soon
