### ISSUE TITLE
🐛 bug: get_balance

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#151]
FYI: I just pulled development & rebuilt the docker container & did the migrations.

**Comment by lgiesen** [comment]
![Image](https://user-images.githubusercontent.com/48908722/208304720-4f95ac2e-06c7-4a87-b28e-5f0e6ce2b46d.png)

But in users/views.py, there should not be an error: 
if user.card_id is not None:
        balance = KlarnaCollector().get_current_balance(user.card_id)
        return Response(balance, status=status.HTTP_200_OK)
    else:
        return Response("No card_id in user profile",
                        status=status.HTTP_404_NOT_FOUND)

**Comment by lgiesen** [comment]
I had some issues with pg admin. I'll just quickly rebuild and see 🤷‍♂️

**Comment by martenjostmann** [comment]
A few day before the klarna service wasn't reachable. Now it should work. Can you verify this?

**Comment by martenjostmann** [comment]
But you are right. When the service is not available there shouldn't be an unbound error. For this see #149

**Comment by lgiesen** [comment]
Yes, balance works again.
