### ISSUE TITLE
Vue Linting error

### ISSUE THREAD

**Issue by martenjostmann** [erikzimmermann/mensa-today#171]
I was trying to start the frontend but I get this error: ERROR  Invalid options in vue.config.js: "rules" is not allowed
Is there a package missing?

Steps to reproduce:
1. docker-compose -f docker-compose.local.yaml down
2. docker-compose -f docker-compose.local.yaml up --build

**Comment by lgiesen** [comment]
It worked with my previous docker build and after reproducing your steps I also don't have an error. I don't understand how it could cause an error with your device. The rules have been defined from the beginning of the project a month ago. The linting (changing the `'` to `"`  should also not cause the error.
![Screenshot 2022-12-24 at 12 40 25](https://user-images.githubusercontent.com/48908722/209434350-29a52d43-9b83-4567-8fb4-da66a941b8d3.png)

**Comment by lgiesen** [comment]
I don't know if it is because of dependencies. The difference in linting packages between the development and linting branch is the following:
development
"devDependencies": {
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    _**"eslint-plugin-vue": "^8.0.3",**_
    "lint": "^0.8.8",
  }
linting:
"devDependencies": {
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    _**"eslint-loader": "^4.0.2",**_
    "eslint-plugin-prettier": "^4.0.0",
    _**"eslint-plugin-vue": "^8.7.1",**_
    "lint": "^0.8.8",
  }

**Comment by martenjostmann** [comment]
![image](https://user-images.githubusercontent.com/47032832/209462530-486a75b0-62f3-40dd-9ae9-a25ecb413815.png)

**Comment by martenjostmann** [comment]
Also every tutorial regarding eslint put there configurations inside of the .eslintrc.js. Maybe you should have a look at this.

**Comment by lgiesen** [comment]
> It worked with my previous docker build and after reproducing your steps I also don't have an error. I don't understand how it could cause an error with your device. The rules have been defined from the beginning of the project a month ago. The linting (changing the `'` to `"` should also not cause the error. ![Screenshot 2022-12-24 at 12 40 25](https://user-images.githubusercontent.com/48908722/209434350-29a52d43-9b83-4567-8fb4-da66a941b8d3.png)

Oh, I searched in the .eslintrc.js instead of the vue.config.js. 

Since, I cannot reproduce the error, it is hard to debug. I followed the following [tutorial](https://vue-loader.vuejs.org/guide/linting.html#eslint). It says to put the rules in the webpack.config.js, but there is none in our project. According to [this StackOverflow thread](https://stackoverflow.com/questions/50304066/webpack-config-missing-in-vuejs), it should be defined in the vue.config.js (which I did previously). I tried to adjust it, but I cannot test if it solves your error. It is weird that I do not receive it.

**Comment by lgiesen** [comment]
note to myself: lint with `cd frontend && npm run lint`, if it doesn't do it already on save
