### ISSUE TITLE
🐛 Dishplan returns empty array

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#229]
the `mensa/get_dishplan` call returns `[]`, even though the mensa is open.
This might be the reason why `mensa/get_recommendations` and `mensa/get_week_recommendation` result in an Error:

![Image](https://user-images.githubusercontent.com/48908722/219590107-6407ef6c-803b-41f7-b8ae-2df45dccd219.png)
![Image](https://user-images.githubusercontent.com/48908722/219590108-85729b84-32b2-4360-8bce-f67857642085.png)

**Comment by martenjostmann** [comment]
The data model have changed. You have to migrate and then collect imensa again.

**Comment by lgiesen** [comment]
I still have some issues. Could we have a look at it together? I tried the following, but now I get multiple 500 Errors (all revolve around `relation "users user" does not exist LINE 1: …..user' "is _superuser", "users_user" "card_id" FROM "users_use...` 

```
docker-compose -f docker-compose.local.yaml down
docker rm -f $(docker ps -a -q)
docker volume rm $(docker volume ls -q)
docker-compose -f docker-compose.local.yaml up --build
docker exec -it data-integration-recommender-app-1 bash
python manage.py collect-all
```
