### ISSUE TITLE
🐛 Leaflet not found

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#256]
![Screenshot 2023-03-28 at 13 35 03](https://user-images.githubusercontent.com/48908722/228224134-50a665c0-e1f1-4a9f-ba00-cc554678407b.png)
Do I need to install something or why is there an error? Or do I need to rebuild?

**Comment by martenjostmann** [comment]
I think you have to stop in reinstall the container as usual

**Comment by lgiesen** [comment]
Ah yeah, just tried. Worked :) ty
