### ISSUE TITLE
Token-Management

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#79]
- [ ] stay signed in after refresh
- [ ] store token in cookie
- [ ] rm cookie on logout

**Comment by martenjostmann** [comment]
Why is this a wontfix?

**Comment by lgiesen** [comment]
Good question :D Maybe because of Persistent state the token is saved without the cookie. Though I have to agree, it is probably better to fix it. I don't know how much time I can invest into the project before the exam phase tbh :/
