### ISSUE TITLE
HomeView.vue: Enable Rating the Dish

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#83]

**Comment by martenjostmann** [comment]
This is a really import feature. @MarcelRe9 can you have a look at this?

**Comment by lgiesen** [comment]
Is this already implemented @MarcelRe9 ?

**Comment by MarcelRe9** [comment]
> Is this already implemented @MarcelRe9 ?

Yes, you even approved my pull request 😂

**Comment by lgiesen** [comment]
🤣 yeah I thought as much, but I wanted to make sure
