### ISSUE TITLE
State Management with PersistendState

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#90]
Token-Management
stay signed in after refresh
store token in cookie
remove cookie on logout

**Comment by lgiesen** [comment]
@MarcelRe9 Do you want to do it?

**Comment by lgiesen** [comment]
@martenjostmann said that he could try it out

**Comment by lgiesen** [comment]
@martenjostmann Is this implemented on [frontend/state-management](https://github.com/erikzimmermann/mensa-today/commit/893ae85b72fe0db6344e65a08e2244360ffa100d)? Able to test & merge?

**Comment by martenjostmann** [comment]
Yeah. You can have a look at pr #184 and review it
